# Generated by Django 5.0.1 on 2026-01-10 09:22

import django.core.validators
import django.db.models.deletion
import user_portal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Browser session identifier for tracking unsaved submissions')),
                ('image', models.ImageField(help_text='Photo of civic complaint (max 5MB)', upload_to=user_portal.models.civic_complaint_image_path, validators=[user_portal.models.validate_image_size])),
                ('street', models.CharField(blank=True, help_text='Street address where complaint photo was taken', max_length=255)),
                ('area', models.CharField(help_text='Area/locality name (e.g., Satellite, Vastrapur)', max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text='PIN code of the location', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate (GPS)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate (GPS)', max_digits=10)),
                ('is_submit', models.BooleanField(db_index=True, default=False, help_text='True if user has submitted complaint, False if only captured')),
                ('is_valid', models.BooleanField(blank=True, help_text='AI validation result: True=valid complaint, False=invalid, None=not yet validated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When photo was captured')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
            ],
            options={
                'verbose_name': 'Civic Complaint',
                'verbose_name_plural': 'Civic Complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_submit', 'created_at'], name='user_portal_is_subm_b5816d_idx'), models.Index(fields=['session_id', 'is_submit'], name='user_portal_session_42c9aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, help_text='Unique ticket number for tracking (CMP-20260110-001)', max_length=20, unique=True)),
                ('severity', models.CharField(help_text='Issue severity level (e.g., Low, Medium, High, Critical)', max_length=50)),
                ('category', models.CharField(help_text='Issue category (e.g., Roads, Sanitation, Drainage)', max_length=100)),
                ('department', models.CharField(help_text='Responsible department (e.g., PWD, Sanitation Dept)', max_length=100)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], db_index=True, default='SUBMITTED', help_text='Current processing status', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, help_text='Citizen rating of work quality (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When ticket was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update timestamp')),
                ('civic_complaint', models.ForeignKey(help_text='Parent complaint that generated this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='user_portal.civiccomplaint')),
                ('contractor', models.ForeignKey(blank=True, help_text='Assigned contractor (visible when status=ASSIGNED)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='admin_portal.contractor')),
                ('ward', models.ForeignKey(blank=True, help_text='Assigned ward (visible when status=IN_PROGRESS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='admin_portal.ward')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='user_portal_status_6a896f_idx'), models.Index(fields=['department', 'status'], name='user_portal_departm_ce2420_idx')],
            },
        ),
    ]
