# Generated by Django 5.0.1 on 2026-01-10 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('Sanitation Department', 'Sanitation Department'), ('Roads & Infrastructure', 'Roads & Infrastructure'), ('Water Supply Department', 'Water Supply Department'), ('Drainage Department', 'Drainage Department')], db_index=True, help_text='Responsible department (standardized from AI classification)', max_length=100),
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('ASSIGNMENT', 'Assignment'), ('COMMENT', 'Comment'), ('SYSTEM', 'System Generated')], default='COMMENT', help_text='Type of note for filtering and display', max_length=20)),
                ('content', models.TextField(help_text='Note content (action description, observations, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When note was created')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who created this note (null for system-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_notes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user_portal.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Note',
                'verbose_name_plural': 'Ticket Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='user_portal_ticket__657f74_idx'), models.Index(fields=['note_type', 'created_at'], name='user_portal_note_ty_bbd7f1_idx')],
            },
        ),
    ]
