# Generated by Django 5.2.10 on 2026-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_alter_ticket_department_ticketnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_verified',
            field=models.BooleanField(db_index=True, default=False, help_text="True if AI has verified contractor's completion photo"),
        ),
    ]
