# Generated by Django 5.2.10 on 2026-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_ticket_ai_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='safety_equipment',
            field=models.TextField(blank=True, help_text="Comma-separated list of required safety equipment (e.g., 'Gloves, Mask, Safety boots')", null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='suggested_tools',
            field=models.TextField(blank=True, help_text="Comma-separated list of recommended tools (e.g., 'Broom, Garbage bags, Shovel')", null=True),
        ),
    ]
