# Generated by Django 5.0.1 on 2026-01-10 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(help_text='Full name or company name of contractor', max_length=150)),
                ('contractor_phone', models.CharField(help_text='Primary contact number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+919876543210' or '9876543210'", regex='^\\+?91?[6-9]\\d{9}$')])),
                ('contractor_email', models.EmailField(help_text='Email address for notifications', max_length=254)),
                ('assigned_area', models.CharField(help_text='Geographic area where contractor operates (e.g., Satellite, Vastrapur)', max_length=200)),
                ('department', models.CharField(help_text='Department specialization (e.g., PWD, Sanitation, Drainage)', max_length=100)),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from citizens (0.00 to 5.00)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When contractor was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
                'ordering': ['-ratings', 'contractor_name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.CharField(db_index=True, help_text='Ward number (e.g., 1, 2A, 3B)', max_length=10, unique=True)),
                ('ward_name', models.CharField(help_text='Official ward name', max_length=100)),
                ('ward_admin_name', models.CharField(help_text='Name of ward administrator', max_length=100)),
                ('ward_admin_no', models.CharField(help_text='Ward administrator contact number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+919876543210' or '9876543210'", regex='^\\+?91?[6-9]\\d{9}$')])),
                ('ward_address', models.TextField(help_text='Complete ward office address')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When ward was added to system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['ward_no'],
            },
        ),
    ]
