# Generated by Django 5.2.10 on 2026-01-10 16:28

import admin_portal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
        ('user_portal', '0003_ticket_ai_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='assigned_area',
        ),
        migrations.AddField(
            model_name='contractor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account for contractor login', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='wards',
            field=models.ManyToManyField(help_text='Wards where contractor can work (one contractor can work in multiple wards)', related_name='contractors', to='admin_portal.ward'),
        ),
        migrations.CreateModel(
            name='TicketCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_image', models.ImageField(help_text='Photo of resolved issue taken by contractor', upload_to=admin_portal.models.contractor_completion_image_path)),
                ('contractor_latitude', models.DecimalField(decimal_places=7, help_text="Contractor's GPS latitude when uploading photo", max_digits=10)),
                ('contractor_longitude', models.DecimalField(decimal_places=7, help_text="Contractor's GPS longitude when uploading photo", max_digits=10)),
                ('distance_from_original', models.DecimalField(decimal_places=2, help_text='Distance in meters from original complaint location', max_digits=7)),
                ('ai_verified', models.BooleanField(db_index=True, default=False, help_text='True if AI confirms work is completed successfully')),
                ('ai_verification_message', models.TextField(blank=True, help_text='AI response message (error details if verification failed)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When contractor submitted completion photo')),
                ('contractor', models.ForeignKey(help_text='Contractor who submitted completion', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='admin_portal.contractor')),
                ('ticket', models.OneToOneField(help_text='Ticket this completion is for', on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='user_portal.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Completion',
                'verbose_name_plural': 'Ticket Completions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('AI_VERIFICATION', 'AI Verification Complete'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_COMPLETED', 'Work Completed')], db_index=True, help_text='Type of notification', max_length=30)),
                ('message', models.TextField(help_text='Notification message to display to admin')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='True if admin has viewed this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When notification was created')),
                ('ticket', models.ForeignKey(help_text='Ticket this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_portal.ticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='admin_porta_is_read_4f159b_idx'), models.Index(fields=['notification_type', 'is_read'], name='admin_porta_notific_d5c850_idx')],
            },
        ),
    ]
